### ISSUE TITLE
authorization issue after restart

### ISSUE THREAD

**Issue by coolcodecding** [Dadoum/anisette-v3-server#23]
I have used a docker setup to fetch BLE tag data from `https://github.com/dchristl/macless-haystack`.
i used this docker-compose:
```  
    anisette:
    image: dadoum/anisette-v3-server
    container_name: findmy_anisette
    networks:
      - findmy_network
    restart: unless-stopped
    stop_grace_period: 1s
    ports:
      - 6969:6969
    volumes:
      - anisette-v3_data:/home/Alcoholic/.config/anisette-v3/lib/
```

First i start anisette server, then i run a setup script that creates a auth.json, which is then read by another service to fetch data from anisette. It works well so far.
However, if i restart anisette, the very same auth.json does not work anymore. This is very unpractical if e.g. the machine reboots and restarts containers, as i dont want to manually auth again with 2FA.

Is there any data stored in memory in anisette that is relevant for auth? What else coult be the reason and how could it be solved?
Any hint is welcome :)
