### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by h4wwk3ye** [Dadoum/anisette-v3-server#8]
Running the container using compose and getting the following error.

```
??:? [0xc25279730faf]
                     app INFO  2023-11-20T10:17:15.770 anisette-v3-server v2.1.0
                     app INFO  2023-11-20T10:17:15.776 Downloading libraries from Apple servers...
                     app INFO  2023-11-20T10:17:17.128 Done !
std.file.FileException@std/file.d(836): /home/Alcoholic/.config/anisette-v3/lib/libCoreADI.so: Permission denied
```

Docker compose

```
  anisette:
    image: dadoum/anisette-v3-server
    container_name: anisette
    ports:
      - '6970:6969'
    volumes:
      - '${DIR}/anisette:/home/Alcoholic/.config/anisette-v3/lib/'
    restart: ${RESTART_MODE}
```

**Comment by genericgod** [comment]
For anyone having this problem, you need to get the UID and GID of your docker user and add it to your run command like this:
`docker run -d --restart always --name anisette-v3 -p 6969:6969 --volume anisette-v3_data:/home/Alcoholic/.config/anisette-v3/lib/ dadoum/anisette-v3-server --user UID:GID`

or with compose:
```
anisette:
    image: dadoum/anisette-v3-server
    container_name: anisette
    ports:
      - '6970:6969'
    volumes:
      - '${DIR}/anisette:/home/Alcoholic/.config/anisette-v3/lib/'
    restart: ${RESTART_MODE}
    user: 'UID:GID'
```

**Comment by jeremy-code** [comment]
Consider the following `docker-compose.yml` and `./anisette` doesn't exist.

```
services:
  anisette:
    container_name: anisette
    image: 'dadoum/anisette-v3-server:latest'
    restart: unless-stopped
    volumes:
      - './anisette/:/home/Alcoholic/.config/anisette-v3/lib'
```

Run `sudo docker compose up`. The directory `./anisette` will be created such that

```sh
ls -ld anisette/
> drwxr-xr-x 2 root root 4096 Mar  9 02:36 anisette/

docker compose up
[+] Running 1/1
 ✔ Container anisette  Created                                                                                              0.0s
Attaching to anisette
anisette  | std.file.FileException@std/file.d(836): /home/Alcoholic/.config/anisette-v3/lib/libCoreADI.so: Permission denied
anisette  | ----------------
anisette  | ??:? [0x63c08106ebf6]
anisette  | ??:? [0x63c08109b386]
anisette  | ??:? [0x63c081079c3f]
anisette  | ??:? [0x63c08103e03a]
anisette  | ??:? [0x63c080e86ef9]
anisette  | ??:? [0x63c08107992b]
anisette  | ??:? [0x63c081079825]
anisette  | ??:? [0x63c08107967d]
anisette  | ??:? [0x728b6e17a249]
anisette  | ??:? __libc_start_main [0x728b6e17a304]
anisette  | ??:? [0x63c080e86450]
anisette  |                      app INFO  2025-03-09T02:39:09.685 anisette-v3-server v2.2.2
anisette  |                      app INFO  2025-03-09T02:39:09.694 Downloading libraries from Apple servers...
anisette  |                      app INFO  2025-03-09T02:39:33.003 Done !
anisette exited with code 0
```

Furthermore,

```sh
sudo docker exec -it anisette id
> uid=1000(Alcoholic) gid=1000(Alcoholic) groups=1000(Alcoholic)
```

where uid=1000 is first nonroot user.

Hence, if you run `sudo chown -R 1000:1000 ./anisette/` (or wherever the directory is on the host machine), the error will be fixed.

**Comment by hheimbuerger** [comment]
Struggled with similar issues, using a Docker compose configuration (Synology Container Manager).

I had to set the `HOME` env var to `/home/Alcoholic` to make it work.

Then this works for me:

```
services:
  anisette:
    container_name: anisette
    image: dadoum/anisette-v3-server
    user: 50000:60000    # set up user and group for my containers under IDs 50000 (user) and 60000 (group)
    network_mode: bridge
    ports:
      - 6969:6969
    volumes:
      - /volume1/containers/anisette/data:/home/Alcoholic/.config/anisette-v3:rw
    environment:
      - HOME=/home/Alcoholic
      - TZ=Europe/Paris
```

For my containers, I have set up a user ID 50000 and a group under ID 60000. The `/volume1/containers` subdirectories are owned by that user/group.
